//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCPData
{
    using System;
    using System.Collections.Generic;
    
    public partial class HCPData
    {
        public int HCPId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> SpecialityId { get; set; }
    
        public virtual SpecialityMaster SpecialityMaster { get; set; }
    }
}
